# Generated by Django 5.0.4 on 2024-09-26 06:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='title'),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='description'
                    ),
                ),
                (
                    'creation_date',
                    models.DateField(
                        blank=True, null=True, verbose_name='creation_date'
                    ),
                ),
                (
                    'rating',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='rating',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('movie', 'movie'), ('tv show', 'tv show')],
                        default='movie',
                        max_length=7,
                        verbose_name='type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'filmwork',
                'verbose_name_plural': 'filmworks',
                'db_table': 'content"."film_work',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='name'
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='description'
                    ),
                ),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'content"."genre',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'full_name',
                    models.CharField(max_length=255, verbose_name='full_name'),
                ),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
                'db_table': 'content"."person',
            },
        ),
        migrations.CreateModel(
            name='GenreFilmWork',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'film_work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='genrefilmworks',
                        to='movies.filmwork',
                        verbose_name='filmwork',
                    ),
                ),
                (
                    'genre',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='genrefilmworks',
                        to='movies.genre',
                        verbose_name='genre',
                    ),
                ),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'film genres',
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(
                related_name='filmwork_set',
                through='movies.GenreFilmWork',
                to='movies.genre',
                verbose_name='genres',
            ),
        ),
        migrations.CreateModel(
            name='PersonFilmWork',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('actor', 'actor'),
                            ('producer', 'producer'),
                            ('director', 'director'),
                            ('writer', 'writer'),
                            ('other', 'other'),
                        ],
                        default='actor',
                        max_length=10,
                        verbose_name='role',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                (
                    'film_work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='personfilmworks',
                        to='movies.filmwork',
                        verbose_name='filmwork',
                    ),
                ),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='personfilmworks',
                        to='movies.person',
                        verbose_name='person',
                    ),
                ),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'film persons',
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(
                related_name='filmwork_set',
                through='movies.PersonFilmWork',
                to='movies.person',
                verbose_name='PersonFilmwork',
            ),
        ),
        migrations.AddConstraint(
            model_name='genrefilmwork',
            constraint=models.UniqueConstraint(
                fields=('film_work', 'genre'), name='film_work_genre_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='personfilmwork',
            constraint=models.UniqueConstraint(
                fields=('film_work', 'person', 'role'),
                name='film_work_person_role_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='filmwork',
            index=models.Index(
                fields=['creation_date', 'rating'],
                name='film_work_creation_rating_idx',
            ),
        ),
    ]
