services:

  fastapi_solution:
    build:
      context: .
      dockerfile: docker/dev/fastapi_solution/Dockerfile
    volumes:
      - postgres_socket:/postgres_socket
      - redis_socket:/redis_socket
      - fastapi_gunicorn_socket:/fastapi_gunicorn_socket
    ports:
      - "9000:9000"
    env_file:
      - docker/dev/env/.conn.env
      - docker/dev/env/.env
      - docker/dev/env/.gunicorn.env
    depends_on: [db, elasticsearch, redis]
    restart: unless-stopped
    networks:
      - theatre_network

  django_app: # В нем находится Nginx
    hostname: theatre-app
    build:
      context: .
      dockerfile: docker/dev/django_app/Dockerfile
    volumes:
      - fastapi_gunicorn_socket:/fastapi_gunicorn_socket
      - postgres_socket:/postgres_socket
      - media:/opt/django_app/media/
    depends_on: [db, ]
    ports:
      - "8000:80"
    env_file:
      - docker/dev/env/.conn.env
      - docker/dev/env/.env
      - docker/dev/env/.gunicorn.env
    restart: unless-stopped
    networks:
      - theatre_network

  etl:
    build:
      context: . 
      dockerfile: docker/dev/etl/Dockerfile
    volumes:
      - ./etl/:/opt/etl/
      - postgres_socket:/postgres_socket
      - postgres_data:/var/lib/postgresql/data/
      - redis_socket:/redis_socket
    ports:
      - "8080:8080"
    env_file:
      - docker/dev/env/.conn.env
      - docker/dev/env/.esl.env
    depends_on: [db, elasticsearch, redis]
    restart: unless-stopped
    networks:
      - theatre_network

  elasticsearch:
    build:
      context: .
      dockerfile: docker/dev/es/Dockerfile
    ports:
      - "9200:9200"
    depends_on: [db, redis]
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    networks:
      - theatre_network

  redis:
    image: redis:7.4.0-alpine
    restart: always
    command: ["/var/lib/redis/redis.conf"]
    volumes:
      - ./docker/dev/redis/redis.conf:/var/lib/redis/redis.conf
      - redis_data:/data
      - redis_socket:/redis_socket
    networks:
      - theatre_network

  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/dev/db/pg.conf:/etc/postgresql/postgresql.conf
      - postgres_data:/var/lib/postgresql/data/
      - postgres_socket:/var/run/postgresql/
    env_file:
      - docker/dev/env/.conn.env
    networks:
      - theatre_network


volumes:
  redis_data:
  redis_socket:
  postgres_data:
  postgres_socket:
  fastapi_gunicorn_socket:
  media:

networks:
  theatre_network:
    driver: bridge
