FROM elasticsearch:8.6.2

COPY ./docker/dev/es/movies.json /usr/share/elasticsearch/movies.json
COPY ./docker/dev/es/load_index.sh /usr/share/elasticsearch/load_index.sh

USER root

RUN chmod +x /usr/share/elasticsearch/load_index.sh

USER elasticsearch

CMD ["/bin/bash", "-c", "\
    elasticsearch & \
    elasticsearch_pid=$! && \
    until curl -s localhost:9200; do \
      echo 'Waiting for Elasticsearch...'; \
      sleep 2; \
    done && \
    /usr/share/elasticsearch/load_index.sh && \
    wait $elasticsearch_pid"]