FROM python:3.12-alpine

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/opt/fastapi_solution

ARG GID=1000
ARG UID=1000
ARG USER=ubuntu

RUN apk add --update --no-cache python3-dev postgresql-dev curl && \
    addgroup -g $GID -S $USER && \
    adduser -S $USER -G $USER --uid "$UID" && \
    mkdir -p /redis_socket && \
    chmod -R 777 /redis_socket && \
    chown -R $USER:$USER /redis_socket && \
    mkdir -p /fastapi_gunicorn_socket && \
    chmod -R 755 /fastapi_gunicorn_socket && \
    chown -R $USER:$USER /fastapi_gunicorn_socket

WORKDIR $APP_HOME

COPY --chown=$USER:$USER ./fastapi_solution $APP_HOME

RUN pip install --no-cache-dir --upgrade pip setuptools && \
    pip install -r $APP_HOME/requirements.txt

CMD ["gunicorn", "-c", "gunicorn.conf.py", "src.main:app"]

EXPOSE 9000

USER $USER
